### ISSUE TITLE
Describe testground capabilities to run hopr-core tests

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#122]

**Comment by 0xjjpa** [comment]
On initial look Testground looks great for testing some of the issues we are currently facing with `hopr-core`, but right now the examples are focused on testing Go-based binaries (e.g. [libp2p Testground plan for DHT](https://github.com/libp2p/test-plans/blob/master/dht/libp2p/addrs.go)). I've opened https://github.com/testground/testground/discussions/1086 as to kickstart a conversation on whether there's any existing effort on the JS ports, and if so, whether we can collaborate. Otherwise we'll need to figure it out another way to test the NAT Traversal setup on a CI/nightly build basis.

**Comment by jjperezaguinaga** [comment]
Ended up pipeing everything to an external file, which so far is working great. See changes in https://github.com/hoprnet/hopr-core/pull/139, let's keep it like this for now.

**Comment by 0xjjpa** [comment]
Closed the wrong issue. An update from the Testground team showcases that there are some efforts on the TypeScript direction but nothing has materialised yet. Will continue pushing updates here.

**Comment by 0xjjpa** [comment]
Managed to reach one of the drivers of supporting Testground on TypeScript. There doesn't seem to be immediate push for now, so will close this. We'll explore on our own whether this is needed and/or if we can adapt the SDK to call `hopr-core`d `js-libp2p` nodes, but will discuss that on our planning.
