### ISSUE TITLE
Required default connectors/dependencies are not included/exposed inside npm package

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#145]
# Introduction
When trying to instantiate `hopr-core`, a `hopr-connector` is required as an option to get started. For the time being, `hopr-core-ethereum` is the default connector for using `hopr-core`. Right now, one needs to add `hopr-core-ethereum` manually to the package using `hopr-core`, which one could argue should be inside `hopr-core` as otherwise it's not possible to run `hopr-core`.

# Task Description
- Include `hopr-core-ethereum` as a default package inside of `hopr-core` and expose an interface able to consume it on initialization.

# Definition of Complete
The task is completed when `hopr-core` does not require any other `@hoprnet` library to get started on its own.

# Testing criteria
- [ ] Create a file called `index.ts` and add `@hoprnet/hopr-core` as a package. Create a new instance with default options w/o having to import any other package. This should look something like `const node = await Hopr.create(Hopr.defaultOptions)`

# Notes
Right now `chat` and `server` look as follows in terms of package dependencies.
```
@hoprnet/hopr-core
    "@hoprnet/hopr-core-connector-interface": "1.3.1-refactor.76c9b25",
    "@hoprnet/hopr-core-ethereum": "0.0.12-refactor.473415f",
    "@hoprnet/hopr-demo-seeds": "1.0.3-refactor.3ad82ff",
    "@hoprnet/hopr-utils": "0.1.6-refactor.61df948",
@hoprnet/hopr-chat
    "@hoprnet/hopr-core": "0.6.16",
    "@hoprnet/hopr-core-connector-interface": "1.2.10-98e08f8",
    "@hoprnet/hopr-core-ethereum": "0.0.12-refactor.473415f",
    "@hoprnet/hopr-demo-seeds": "1.0.3-refactor.3ad82ff",
    "@hoprnet/hopr-utils": "0.1.6-refactor.61df948",
```
after this task, these should look as follows:
```
@hoprnet/hopr-core
    "@hoprnet/hopr-core-connector-interface": "1.3.1-refactor.76c9b25",
    "@hoprnet/hopr-core-ethereum": "0.0.12-refactor.473415f",
    "@hoprnet/hopr-demo-seeds": "1.0.3-refactor.3ad82ff",
    "@hoprnet/hopr-utils": "0.1.6-refactor.61df948",
@hoprnet/hopr-chat
    "@hoprnet/hopr-core": "0.6.16",
```

**Comment by 0xjjpa** [comment]
Sadly this one didn't fit in our current focus and workload, moving to Sprint 10.

**Comment by nionis** [comment]
- connector option in `@hoprnet/hopr-core` is now optional
- default connector is set to `@hoprnet/hopr-core-ethereum`
- removed `@hoprnet/hopr-core-ethereum` from `chat` and `server`

couldn't make `@hoprnet/hopr-chat` package.json look like the example above, this is because both `chat` and `server` depend on packages like `@hoprnet/hopr-utils` for their own use
