### ISSUE TITLE
Provide test coverage on hopr-server

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#163]
- [ ] Provide coverage using jest, and generate ready to use tap reports
- [ ] Integrate GitHub bot able to showcase coverage change in PRs
- [ ] Integrate GitHub action able to fail if coverage goes <x%, disable for now.

**Comment by 0xjjpa** [comment]
Moving to Sprint 9.

**Comment by 0xjjpa** [comment]
@nionis Can you check if you can install `coveralls`?

**Comment by nionis** [comment]
@jjperezaguinaga I can't, asked @SCBuergel to install it for me

**Comment by nionis** [comment]
After our meeting with @SCBuergel we decided to move this to Sprint 10 and focus on some other new issues
