### ISSUE TITLE
Extract logs into JSON file format from a running HOPR core node

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#203]
- [ ] Provide the required flags (e.g. `DEBUG=libp2p:*,hopr:*`) to log modules activity into STDOUT
- [ ] Provide the require modifiers to ensure logs are in JSON format

Before
```
node chat/lib/index.js 2>log.txt
```

After
```
node chat/lib/index.js 2>log.json
````

HOPR
```
js-libp2p => hopr
```
Filecoin
```
go-libp2p => filecoin_node, log_server
```

**Comment by nionis** [comment]
After our meeting with @SCBuergel we decided to move this to Sprint 10 and focus on some other new issues
