### ISSUE TITLE
Create AVADO HOPR UI to interact with gRPC Web Server

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#210]

**Comment by 0xjjpa** [comment]
Reassigning this to @peterbraden, but we still have #220, which would be a reference for this one.

**Comment by peterbraden** [comment]
I assume this needs to wait for #220?

**Comment by nionis** [comment]
@peterbraden you can wait for #220 which will be a good reference, you can also use [hopr-mazebot](https://github.com/hoprnet/hopr-mazebot/tree/03f648305667ec693cc6b9a4d881f92937f141ef/canvas-game/ts) as a reference, [index.ts](https://github.com/hoprnet/hopr-mazebot/blob/03f648305667ec693cc6b9a4d881f92937f141ef/canvas-game/ts/index.ts)
