### ISSUE TITLE
Create web application able to talk to web server

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#220]
- [x] Create folder called `web-client` inside `hopr/core` 
- [x] Able to be served in the browser (e.g. 127.0.0.1/index.html) using React
- [x] Able to connect to a web server given a specific IP
- [x] Able to send messages to that webserver
- [x] Able to listen to messages from that webserver

**Comment by 0xjjpa** [comment]
@nionis Do you think it might make sense to already put together an `sdk` for the web server as to quickly allow web clients to talk to it? I think we already have the `protos` so it should be something even simpler that already includes them. Thoughts?

**Comment by nionis** [comment]
@jjperezaguinaga Yeah, we can for sure simplify everything with an sdk, it's something good to have that will make the entry to HOPR easier.

brainstorming:

```javascript
import HoprSDK from "@hoprnet/hopr-web-sdk"

const sdk = new HoprSDK("http://127.0.0.1:8080", {
  credentials: {}
})

// retain service name
const hoprAddress = await sdk.address.getHoprAddress()
const stream = await sdk.listen.listen()

// OR

// flatten
const hoprAddress = await sdk.getHoprAddress()
const stream = await sdk.listen()

await sdk.disconnect()
```

**Comment by nionis** [comment]
I am working on a bare bones chat web app similar to telegram, currently adding support of https://github.com/hoprnet/hopr-chat/pull/15

**Comment by nionis** [comment]
Let's close this and continue the work on a different PR, mainly improve the UI a bit.

Closed by https://github.com/hoprnet/hopr-webapp-demo/pull/1
