### ISSUE TITLE
First ping fails

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#222]
**Describe the bug**
First ping will result to error `Could not ping node. Error was: node unreachable`, but second ping and pings after that will be successful.

**To Reproduce**

1. Start `hopr-chat`
2. ping a node
3. ping a node again

**Expected behavior**
First ping should be successful

**Desktop (please complete the following information):**

- OS: Windows 10
- hopr-chat version: `1.1.9-testnet`

**Comment by 0xjjpa** [comment]
@nionis can you try to replicate this on testnet with another testnet node running outside a VM?

**Comment by robertkiel** [comment]
@nionis this seems to be fixed with the latest update of the network stack.
