### ISSUE TITLE
hopr-server becomes unresponsive when it's running under docker

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#223]
**Describe the bug**
After querying `getStatus` a few times, `hopr-server` will become unresponsive.
This issue appears only when using the docker image.

**To Reproduce**

1. Run `docker run -p 50051:50051 -p 9091:9091 -it gcr.io/hoprassociation/hopr-server@sha256:2e0fdba2421efaeb6d592f6cc872a07e5fae065926e8cc7f0a39e4346f7ffa2b`
2. Using `BloomRPC` or similar query `getStatus`, (first response will be slow)
3. Repeat a few times until there is no response

**Expected behavior**
Server should return `getStatus` results without becoming unresponsive.

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by 0xjjpa** [comment]
Solved in `hopr/server:latest` by changing image from `alpine` to `buster`. Sadly that double the image size, but that's something we'll have to deal with for now.
