### ISSUE TITLE
Segmentation fault directly after getting results from first "crawl"

### ISSUE THREAD

**Issue by greve** [hoprnet/hopr-core#224]
**Describe the bug**
Chat application segfaults on Linux directly after first crawl:

```
> crawl
> Crawling results:
    contacted nodes:: 
        16Uiu2HAmPyq9Gw93VWdS3pgmyAWg2UNnrgZoYKPDUMbKDsWhzuvb
        16Uiu2HAm6VH37RG1R4P8hGV1Px7MneMtNc6PNPewNxCsj1HsDLXW
        16Uiu2HAmCXAmPFSQBSYvNcVfREzELNDw5fVknFe4EUfp3sCqZzNu
    new nodes: 19 nodes
    total: 19 nodes
> ./start-hopr-chat.sh: line 4:  8591 Segmentation fault      (core dumped) node index.js -p switzerland 2> log.txt
```
with the following message in the log:

`(node:9169) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**To Reproduce**
Did a couple of crawls afterwards, but no more segfaults.

Perhaps a code path that is only used upon first setup?

**Desktop (please complete the following information):**

- OS: Fedora Linux

**Comment by 0xjjpa** [comment]
Hey @greve, thanks for pointing this one out. How did you start the application? We have seen this happening in our `Docker` images, but not so much in our “binary” releases. Also, do you happen to have which `node` version you have installed?

Thanks for reporting this!

**Comment by greve** [comment]
Hi @jjperezaguinaga - I started it from the shell via "./start-hopr-chat.sh".

Node.js is current version in Fedora: 

```
node -v
v12.16.3
```

You're welcome and let me know if I can help in any other way!
