### ISSUE TITLE
hopr-core test suite fails

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#231]
**Describe the bug**
tests fail at least 75% of the time

**To Reproduce**

1. Run `yarn test`

**Expected behavior**
Tests should pass, if some of them are WIP they can be `skipped`, the end goal is to re-enable `hopr-core` test suite in our CI.

**Additional context**
taken from riot:
> currently when making a PR to `hopr-core`, we don't run any tests of `hopr-core` because they seem to fail at least 75% of the time (sometimes they do pass though), tests are disabled by omitting `core` in [this line](https://github.com/hoprnet/hopr-core/blob/5150137194182a0cd39f92aac2185fa3822b6ef0/.github/workflows/nodejs.yml#L17)

**To do**

- [x] fix test suite so it passes
- [x] re-enable `core` tests in [workflow](https://github.com/hoprnet/hopr-core/blob/5150137194182a0cd39f92aac2185fa3822b6ef0/.github/workflows/nodejs.yml#L17)

**Comment by robertkiel** [comment]
The problem happens because Jest is using parallel testing and the unit tests listen to specific ports instead of dynamically chosen ones.

Concurrent testing will therefore produce `EADDRINUSE` errors.

**Comment by nionis** [comment]
@robertkiel feel free to re-enable CI tests in [this workflow](https://github.com/hoprnet/hopr-core/blob/5150137194182a0cd39f92aac2185fa3822b6ef0/.github/workflows/nodejs.yml#L17) once fixed 👍

**Comment by robertkiel** [comment]
Tests are working again. Needed to run them `--runInBand` and sequentionally through `maxConcurrency: 1`

**Comment by peterbraden** [comment]
Reenabled in #256
