### ISSUE TITLE
Remove tags unrelated to hopr-core

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#233]
- [ ] Remove all tags that are not in the format `0.6.x` from the project. To remove a tag, just push `git push origin :tag`

**Comment by 0xjjpa** [comment]
Definitely confusing for a newcomer. We definitely need to stick to a pattern:

- Keep the `v`?
- Add namespace? e.g. `hopr-core@$version`

**Comment by 0xjjpa** [comment]
After discussing with @peterbraden we agreed to move away from the monorepo setup as to avoid these issues. We'll change this task to remove the old tags and stick to `hopr-core` tags for the time being.

**Comment by peterbraden** [comment]
I kept both X.X.X and vX.X.X
