### ISSUE TITLE
Remove lodash as a dependency from all projects

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#234]
- [x] Grep all projects and remove lodash.
- [ ] Close all lodash issues from dependabot

**Comment by robertkiel** [comment]
Lodash seems to be a (sub)* depedency of some dependencies. Fixed for the moment by installing minor fixes of our dependencies

**Comment by 0xjjpa** [comment]
Seems like it's already being pushed and solved in all repos.
