### ISSUE TITLE
implement grpc proxy for hopr-server

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#239]
gRPC-Web browser clients connect to gRPC services via a special gateway proxy, this can be done by a proxy like [envoy](https://blog.envoyproxy.io/envoy-and-grpc-web-a-fresh-new-alternative-to-rest-6504ce7eb880) or [nginx](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/docker/nginx)

related issues: [1](https://github.com/nestjs/docs.nestjs.com/issues/240), [2](https://github.com/grpc/grpc-web#grpc-web)

**Comment by 0xjjpa** [comment]
Can you setup a `docker-compose.yml` to setup the `envoy` or `nginx` proxy to talk to the server?

**Comment by 0xjjpa** [comment]
Already completed this in https://github.com/hoprnet/mazebot/blob/master/docker-compose.yaml, so you can reuse the `proxy` code there.

**Comment by nionis** [comment]
@jjperezaguinaga

goal:
- move the envoy folder into it's own repository
- include in `hopr-server` a `docker-compose` file that includes `server` and `envoy`

thoughts?

**Comment by 0xjjpa** [comment]
@nionis The `envoy` part is too small to be in its own repo IMHO. Maybe we can just keep it in `server`, as we won't ever use it w/o `server` anyway. Yay or nay?

**Comment by nionis** [comment]
@jjperezaguinaga Yay, let's do as we discussed in the call: `hopr-server` dockerfile should start `hopr-server` and `envoy` managed by something like `pm2` or similar

**Comment by nionis** [comment]
Closed by https://github.com/hoprnet/hopr-server/pull/2
