### ISSUE TITLE
Setup AVADO node locally

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#248]
- [x] Setup the AVADO node locally, and kickstart VPN service.
- [x] Create VPN credentials and share them within the team.

**Comment by peterbraden** [comment]
@jjperezaguinaga where are the AVADO developer docs?

**Comment by 0xjjpa** [comment]
The sample repo is on https://github.com/AvadoDServer/AVADO-DNP-HOPR-core. Other sample AVADO apps are available on https://github.com/AvadoDServer/webapp-demo. Their quickstart is also available after you plug on the node and connect to it via their Wifi.

**Comment by peterbraden** [comment]
VPN isn't going to work as our router isn't supporting UPnP, however everyone in the office can login with the wifi creds available in the paper documentation.
