### ISSUE TITLE
Refactor repo structure into separate repositories

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#249]
- [x] Refactor our folders into their respective repository
  - [x] Move `chat` into https://github.com/hoprnet/hopr-chat.
  - [x] Move `server` into https://github.com/hoprnet/hopr-server.
  - [x] Move `protos` into https://github.com/hoprnet/hopr-protos.
- [x] Fix the `.github/workflows` pipelines to ensure they work in their new repos.
  - [x] `node.yaml` should run the project's test suite on PR.
  - [x] `publish.yaml` should do the following on tag push
    - [x] create a binary and docker image for `chat`
    - [ ] create a docker image for `server`
    - [x] publish an npm package for `protos`

The best way to ensure this is properly working,
- [ ] Create a PR with a new feature e.g. `feature/increase-version`
- [ ] Add the label `minor patch` and `merge when passing`, this will run the `node.yaml` action
- [ ] On merge RangerBot will create a tag that will trigger the `publish.yaml` action.

**Comment by peterbraden** [comment]
[ ] Port over open PR for Protos
