### ISSUE TITLE
Provide version on top of libp2p protocol module

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#266]
# Introduction
Right now all hopr nodes are able to speak on the same version. This is not a problem, but can eventually be backwards compatible moving forward. It's worth adding a version-based namespace that is able to block/allow access to other nodes.

# Task Description
- [ ] Add `$VERSION` to the `libp2p` protocol implementation of `hopr-core` as to isolate communication.

**Comment by robertkiel** [comment]
Done with #285
