### ISSUE TITLE
Update hopr-core w/latest version of hopr-core-ethereum deployed in xDai Chain

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#282]
See https://github.com/hoprnet/hopr-core-ethereum/issues/96.

- [x] Update package.json to match the latest version of `hopr-core-ethereum` that has the contracts deployed in the xDai Chain.
- [x] Push a new version of `hopr-core` to `npm` with a `xdai` suffix to showcase its connection to the `xdai` network.

**Comment by nionis** [comment]
Fixed in #287
