### ISSUE TITLE
Implement describe command

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-core#51]
Displays `hopr-core`, `hopr-chat`, `hopr-*` versions, along with other data unique to the active connector.

**Comment by 0xjjpa** [comment]
I ended up copying the `package.json` of the `hopr-chat` into the `lib` folder and requiring it on runtime, logging its contents on start. Check the changes [here](https://github.com/hoprnet/hopr-core/blob/42cba99884dec2b006bfa18a877e25721016c56b/chat/index.ts), which are part of the NAT traversal [PR](https://github.com/hoprnet/hopr-core/pull/62).
