### ISSUE TITLE
Refactor HOPR-chat to allow default behaviour to be single hops and enable multi-hops on request

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core#72]
- [x] Refactor code to ignore questions about hop selection
- [x] Read `ENABLE_MULTIHOP` environment variable to allow existing behaviour of checking nodes and selecting them.

**Comment by 0xjjpa** [comment]
To be merged in #72

**Comment by 0xjjpa** [comment]
Latest image already has this one, so no longer blocks the documentation task - https://hub.docker.com/r/hopr/chat

**Comment by nionis** [comment]
Fixed by #73
