### ISSUE TITLE
Redeem tickets

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-core#79]
Whenever a node receives a packet, it stores the unacknowledged packets in the database and replaces these entries by acknowledged packets once it receives the acknowledgement.

Winning tickets should be redeemed.

**Comment by nionis** [comment]
@robertkiel When we were discussing on who should be storing tickets (`hopr-core` vs `hopr-core-ethereum`), the conclusion was to go for `hopr-core`.
To do that I implemented [this](https://github.com/hoprnet/hopr-core-ethereum/blob/9d77cb9133bbf20a352c9691ab2ba17d51032ff5/src/tickets/index.ts#L7) so it can be used by `hopr-core`.

Doesn't it make more sense for `hopr-core-ethereum` to store tickets and only use `hopr-core` store unacknowledged  / acknowledged  packets?
I also see that this [issue](https://github.com/hoprnet/hopr-core-ethereum/issues/44) was created for `hopr-core-ethereum` which makes me think that we are on the same page here.
