### ISSUE TITLE
Testnet Initial Release

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-core#8]

**Comment by 0xjjpa** [comment]
As additional thoughts in here, our goal is:

- Enable anyone to run a HOPR-chat node using Docker by running the instructions at the bottom of this comment (pending documentation)
- Using HOPR-chat, send messages using 0 hops to another connected user
- Ensure 0 hop messages require 0 HOPR tokens.
- Showcase proof-of-testnet across all major OS (e.g. Ubuntu, OSX, Windows *)

## Env Variables
```
HOPR_PORT=9091 \
HOST_IPV4=0.0.0.0:$HOPR_PORT \
DOCKER_IMAGE=gcr.io/hoprassociation/hopr-core:latest \
BOOTSTRAP_SERVERS=$COUNTRY_BOOTSTRAP_NODE \
ETHEREUM_PROVIDER=wss://kovan.infura.io/ws/v3/$INFURA_ID \
PORTS=$HOPR_PORT:$HOPR_PORT
```

## Docker Commands

**Windows**
```
docker run -v %cd%/db:/app/db -e HOST_IPV4=0.0.0.0:9091 -e BOOTSTRAP_SERVERS=$COUNTRY_BOOTSTRAP_NODE -e ETHEREUM_PROVIDER=wss://kovan.infura.io/ws/v3/$INFURA_ID -p 9091:9091-it gcr.io/hoprassociation/hopr-core:latest -p 123456
```

**OSX/Linux**
```
docker run -v $(pwd)/db:/app/db -e HOST_IPV4=$HOST_IPV4 -e BOOTSTRAP_SERVERS=$BOOTSTRAP_SERVERS -e ETHEREUM_PROVIDER=$ETHEREUM_PROVIDER -p $PORTS -it $DOCKER_IMAGE -p 123456
```

**Comment by 0xjjpa** [comment]
We have deployed 3 bootstrap nodes for our testnet launch. 

- ✅ `/dns4/ch-test-01.hoprnet.io/tcp/9091/p2p/16Uiu2HAm2n7Lfn76Ex7JnesxXjCtoPbLA6S1Q3boEELETBCD9RKc`
- ✅ `/dns4/ch-test-02.hoprnet.io/tcp/9091/p2p/16Uiu2HAm9YbgfQ5yAPQ99ZgfCdJKcdn7tZ2xDBwvaaitfvXGgD2d`
- ✅ `/dns4/ch-test-03.hoprnet.io/tcp/9091/p2p/16Uiu2HAmSDWT1xhYc7CYEunDoVY21aWA5LpXTTqZpxymFB34FFjH`

They are the equivalent of these ones.

- ✅ `/ip4/34.65.200.251/tcp/9091/p2p/16Uiu2HAm2n7Lfn76Ex7JnesxXjCtoPbLA6S1Q3boEELETBCD9RKc`
- ✅ `/ip4/34.65.51.50/tcp/9091/p2p/16Uiu2HAm9YbgfQ5yAPQ99ZgfCdJKcdn7tZ2xDBwvaaitfvXGgD2d`
- ✅ `/ip4/34.65.69.119/tcp/9091/p2p/16Uiu2HAmSDWT1xhYc7CYEunDoVY21aWA5LpXTTqZpxymFB34FFjH`

There are more to come here (i.e. status, different countries, etc), but it will be important for us to keep these ones in mind for now as we manage our documentation. 

**Word of caution**: As these bootstrap nodes are still in the works, sometimes they might need to be restarted and HOPR-chat nodes might fail to connect to them.

**Comment by 0xjjpa** [comment]
We have concluded our initial testnet release! Up to date docs, both in `nodejs` and `docker` are available in https://docs.hoprnet.io/home/. Closing epic.
