### ISSUE TITLE
[ bounty ] Test NAT traversal module

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-core#87]
Our transport module needs to work on as many as possible configurations as possible. Hence, we need to test the networking stack and our transport module carefully.

- [ ] install `hopr-chat` on two separate Windows machines, `windowsA` and `windowsB`
- [ ] select one bootstrap node from our [bootstrap nodes](https://docs.hoprnet.io/home/getting-started/quickstart/windows-quickstart#bootstrap-nodes), `bootstrapA`
- [ ] set environment variable `DEBUG=hopr-core:transport`
- [ ] connect `windowsA` to `bootstrapA`
- [ ] connect `windowsB` through a mobile hotspot to `bootstrapA`
- [ ] send a "Hello World" message from `windowsA` to `windowsB`
- [ ] send a "Pong" message from `windowsB` to `windowsA`
- [ ] restart `windowsA` and connect it through **another** mobile hotspot to `bootstrapA`
- [ ] send a "Hello World" message from `windowsA` to `windowsB`
- [ ] send a "Pong" message from `windowsB` to `windowsA`

Not all of these test might work and the purpose of this issue is to detect which of them do not work. The environment variable `DEBUG=hopr-core:transport` will print the debug messages to the command-line. Please document the tests by inserting the debug messages as well as the interfaces that you have used, e.g. `/ip4/34.65.237.196/tcp/9091/p2p/16Uiu2HAmThyWP5YWutPmYk9yUZ48ryWyZ7Cf6pMTQduvHUS9sGE7`. Also, let us know if you experience any inconvenience with `hopr-chat`

**Comment by 0xjjpa** [comment]
We'll provide more detailed information about this one in the docs and in an actual bounty. For now I think we can close this one if needed we'll put together a more detailed page.
